excluded:
- Pods
- Development Pods
  
disabled_rules:
- trailing_whitespace
- identifier_name
- force_cast
- file_length
- line_length
- type_name
- cyclomatic_complexity
- redundant_string_enum_value
- force_try
- shorthand_operator
- function_body_length
- type_body_length
- closure_parameter_position
- large_tuple
- block_based_kvo
- multiple_closures_with_trailing_closure
- for_where
- valid_ibinspectable
- orphaned_doc_comment
- compiler_protocol_init
- function_parameter_count
- deployment_target
- nesting
